"use client";

import { useState } from "react";
import { Check, Loader2, Send } from "lucide-react";

interface FormData { name: string; email: string; organization: string; audience: string; message: string; }
const EMPTY: FormData = { name: "", email: "", organization: "", audience: "", message: "" };

export function BriefingForm() {
  const [submitted, setSubmitted] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [data, setData] = useState<FormData>(EMPTY);
  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setData((previous) => ({ ...previous, [e.target.name]: e.target.value }));
  const handleSubmit = async (e: React.FormEvent) => { e.preventDefault(); setSubmitting(true); await new Promise((resolve) => setTimeout(resolve, 500)); setSubmitting(false); setSubmitted(true); };

  if (submitted) return <div className="evidence-sheet flex min-h-96 flex-col items-center justify-center text-center" role="status"><span className="flex h-14 w-14 items-center justify-center bg-primary-soft"><Check className="h-6 w-6 text-primary"/></span><h3 className="mt-6 text-xl font-semibold">Request received</h3><p className="mt-3 max-w-md text-sm leading-relaxed text-ink-muted">Thank you, {data.name || "there"}. We’ll review the context and respond within one business day with the right next step.</p><button type="button" onClick={() => { setSubmitted(false); setData(EMPTY); }} className="mt-7 text-sm font-semibold text-primary hover:underline">Submit another request</button></div>;

  const inputClass = "w-full border border-border bg-background px-4 py-3 text-sm text-foreground outline-none transition-colors placeholder:text-ink-faint focus:border-primary focus:ring-1 focus:ring-primary";
  return <form onSubmit={handleSubmit} className="evidence-sheet"><div className="flex items-center justify-between border-b border-border pb-5"><div><p className="font-mono text-[0.68rem] uppercase text-ink-muted">Confidential enquiry</p><h3 className="mt-2 text-lg font-semibold">Request a briefing</h3></div><span className="font-mono text-[0.65rem] text-ink-muted">* Required</span></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="form-field">Full name *<input name="name" required autoComplete="name" value={data.name} onChange={handleChange} placeholder="Your name" className={inputClass}/></label><label className="form-field">Work email *<input name="email" type="email" required autoComplete="email" value={data.email} onChange={handleChange} placeholder="name@organisation.org" className={inputClass}/></label><label className="form-field">Organisation<input name="organization" autoComplete="organization" value={data.organization} onChange={handleChange} placeholder="Department or institution" className={inputClass}/></label><label className="form-field">I represent<select name="audience" value={data.audience} onChange={handleChange} className={inputClass}><option value="">Select an audience</option><option>Government / public sector</option><option>Enterprise / GCC</option><option>Civic / research institution</option><option>Media</option><option>Other</option></select></label><label className="form-field sm:col-span-2">What should the conversation cover?<textarea name="message" rows={3} value={data.message} onChange={handleChange} placeholder="The institutional problem, operating context, or evidence need…" className={`${inputClass} resize-none`}/></label></div><div className="mt-7 flex flex-col gap-4 border-t border-border pt-6 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-sm text-xs leading-relaxed text-ink-muted">Your details are used only to respond to this enquiry.</p><button type="submit" disabled={submitting} className="action-primary disabled:cursor-not-allowed disabled:opacity-60">{submitting ? <><Loader2 className="h-4 w-4 animate-spin"/>Submitting…</> : <><Send className="h-4 w-4"/>Submit request</>}</button></div></form>;
}