import { ArrowRight, BookOpen, Building2, Check, CircleDot, FileCheck2, FileText, Globe2, Handshake, Landmark, Layers3, LockKeyhole, Microscope, Network, Scale, SearchCheck, ShieldCheck, Workflow } from "lucide-react";
import { BriefingForm } from "./BriefingForm";

function SectionHeading({ eyebrow, title, intro }: { eyebrow: string; title: string; intro?: string }) {
  return <div className="max-w-3xl"><p className="eyebrow">{eyebrow}</p><h2 className="mt-5 text-3xl leading-tight font-semibold text-balance sm:text-4xl">{title}</h2>{intro && <p className="mt-5 text-base leading-relaxed text-ink-muted">{intro}</p>}</div>;
}

const AUDIENCES = [
  { id: "government", icon: Landmark, number: "01", title: "Government & public sector", lead: "Infrastructure designed around public-sector reality—not retrofitted from enterprise SaaS.", needs: ["Connected registries and service data", "Multilingual citizen service layers", "Workflow accountability across departments"], action: "Request a government briefing" },
  { id: "enterprise", icon: Building2, number: "02", title: "Enterprise & GCCs", lead: "Public-sector-grade rigour for compliance, governance, and audit-readiness.", needs: ["Regulatory change tracking", "Evidence-ready audit trails", "Responsible data and AI governance"], action: "Book an enterprise demo" },
  { id: "research", icon: Microscope, number: "03", title: "Civic & research institutions", lead: "Transparent methods and public-interest infrastructure for institutions that need evidence they can interrogate.", needs: ["Published methodology standards", "Open and reusable data structures", "Clear funding and provenance disclosures"], action: "Discuss a research partnership" },
];

export function AudienceSection() {
  return <section id="solutions" className="section-pad bg-background"><div className="content-shell"><SectionHeading eyebrow="Solutions by audience" title="Three institutional contexts. No generic buyer journey." intro="Start with the environment you operate in. Each pathway reflects its own procurement language, accountability standards, and definition of value." /><div className="mt-14 grid border-t border-l border-border lg:grid-cols-3">{AUDIENCES.map((a) => <article key={a.id} id={a.id} className="border-r border-b border-border bg-surface p-7 lg:p-9"><div className="flex items-center justify-between"><a.icon className="h-7 w-7 text-primary" aria-hidden="true"/><span className="font-mono text-xs text-ink-muted">{a.number}</span></div><h3 className="mt-8 text-xl font-semibold">{a.title}</h3><p className="mt-4 min-h-20 text-sm leading-relaxed text-ink-muted">{a.lead}</p><ul className="mt-7 space-y-3 border-t border-border pt-6">{a.needs.map((n) => <li key={n} className="flex gap-3 text-sm"><Check className="mt-0.5 h-4 w-4 shrink-0 text-primary" aria-hidden="true"/>{n}</li>)}</ul><a href="#contact" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-primary">{a.action}<ArrowRight className="h-4 w-4"/></a></article>)}</div></div></section>;
}

const PRODUCTS = [
  { icon: Layers3, title: "Civic Data & Constituent Intelligence", text: "A governed registry and relationship layer for departments that should not have to build one from scratch." },
  { icon: Globe2, title: "Narrative & Media Intelligence", text: "Multilingual monitoring of how policy and public services are discussed in the languages people use." },
  { icon: Workflow, title: "GovTech Workflow & Identity", text: "Permit, grievance, and service workflows designed to connect with existing public digital infrastructure." },
  { icon: Scale, title: "Compliance & Regtech", text: "Regulatory tracking and audit tooling designed around India’s compliance calendar and operating context." },
  { icon: SearchCheck, title: "Research & Policy Intelligence", text: "Field research, legislative tracking, and policy dashboards for decisions that require local evidence." },
  { icon: Handshake, title: "Fundraising & CSR Infrastructure", text: "A donor and grant-management layer connecting CSR mandates with accountable civic programmes." },
];

export function ProductsSection() {
  return <section id="products" className="section-pad border-y border-border bg-contrast"><div className="content-shell"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr]"><SectionHeading eyebrow="What we build" title="One public-interest infrastructure layer. Six product families." intro="Modular enough to enter through one operational need; coherent enough to become shared infrastructure across an institution."/><div className="system-map"><div className="system-core"><Network className="h-6 w-6"/><span>PUBLYTICS<br/><small>DATA + AI CORE</small></span></div>{PRODUCTS.map((p, i) => <article key={p.title} className="system-node"><span className="font-mono text-[0.65rem] text-primary">0{i + 1}</span><p.icon className="h-5 w-5 text-primary" aria-hidden="true"/><h3 className="text-sm font-semibold leading-snug">{p.title}</h3><p className="text-xs leading-relaxed text-ink-muted">{p.text}</p></article>)}</div></div></div></section>;
}

const AI_ROWS = [
  { label: "Where AI is used", text: "Classification, multilingual retrieval, anomaly detection, summarisation, and decision support within defined workflows." },
  { label: "What it does not do", text: "AI does not make high-impact public decisions, determine eligibility, or operate as a political persuasion system." },
  { label: "Human review", text: "People remain accountable for interpretation, escalation, approval, and any action that affects a person or institution." },
];

export function AiSection() {
  return <section id="ai" className="section-pad bg-ink text-inverse"><div className="content-shell"><div className="grid gap-14 lg:grid-cols-2 lg:items-start"><div><p className="eyebrow text-live">AI at Publytics</p><h2 className="mt-5 text-3xl leading-tight font-semibold text-balance sm:text-4xl">Every product uses AI somewhere. We state exactly where—and where it does not.</h2><p className="mt-6 text-base leading-relaxed text-inverse-muted">Institutional trust requires bounded systems, not broad claims. Our standing disclosure pattern makes automation, limits, and human accountability legible before procurement begins.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#trust" className="action-inverse">Read our AI principles <ArrowRight className="h-4 w-4"/></a><a href="#contact" className="action-outline-inverse">Discuss AI governance</a></div></div><div className="border-t border-inverse-border">{AI_ROWS.map((row, i) => <div key={row.label} className="grid gap-3 border-b border-inverse-border py-6 sm:grid-cols-[2rem_10rem_1fr]"><span className="font-mono text-xs text-live">0{i + 1}</span><h3 className="text-sm font-semibold">{row.label}</h3><p className="text-sm leading-relaxed text-inverse-muted">{row.text}</p></div>)}</div></div><div id="trust" className="mt-16 grid gap-px bg-inverse-border md:grid-cols-3"><div className="bg-ink-soft p-6"><Globe2 className="h-5 w-5 text-live"/><h3 className="mt-4 font-semibold">Tamil-first, multilingual</h3><p className="mt-2 text-sm leading-relaxed text-inverse-muted">Designed for Indian-language, dialect, and code-mixed contexts—not English-first assumptions.</p></div><div className="bg-ink-soft p-6"><ShieldCheck className="h-5 w-5 text-live"/><h3 className="mt-4 font-semibold">Data stays bounded</h3><p className="mt-2 text-sm leading-relaxed text-inverse-muted">Client constituent data is not used to train models outside the client’s governed environment.</p></div><div className="bg-ink-soft p-6"><LockKeyhole className="h-5 w-5 text-live"/><h3 className="mt-4 font-semibold">Non-partisan by design</h3><p className="mt-2 text-sm leading-relaxed text-inverse-muted">We do not sell political targeting or persuasion systems to parties or candidates.</p></div></div></div></section>;
}

const SERVICES = [
  { n: "01", title: "Advisory & strategy", text: "Frame the institutional problem, operating model, evidence base, and procurement pathway before technology decisions are made." },
  { n: "02", title: "Data & research as a service", text: "Produce field research, policy intelligence, data models, and recurring evidence products with documented methods." },
  { n: "03", title: "Implementation & integration", text: "Connect workflows, registries, and reporting layers to the systems already in place rather than forcing replacement." },
  { n: "04", title: "Managed services & support", text: "Operate critical research and intelligence workflows with defined governance, review, and service accountability." },
];

export function ServicesSection() {
  return <section id="services" className="section-pad bg-background"><div className="content-shell"><SectionHeading eyebrow="How we work" title="From institutional question to operating infrastructure." intro="Engage Publytics for a focused research mandate, a platform implementation, or a managed capability—with the same standards of evidence and accountability."/><div className="mt-14 grid gap-x-8 border-t border-border md:grid-cols-2 lg:grid-cols-4">{SERVICES.map((s) => <article key={s.title} className="border-b border-border py-8"><p className="font-mono text-xs text-primary">{s.n}</p><h3 className="mt-5 text-lg font-semibold">{s.title}</h3><p className="mt-3 text-sm leading-relaxed text-ink-muted">{s.text}</p></article>)}</div></div></section>;
}

export function RigourSection() {
  return <section id="insights" className="section-pad border-y border-border bg-surface"><div className="content-shell"><div className="grid gap-12 lg:grid-cols-[1fr_1.1fr]"><div><SectionHeading eyebrow="Proof of rigour" title="The method is part of the product." intro="Every published tracker or research output should make its evidence inspectable: what was measured, how it was collected, who funded it, when it changed, and what its limitations are."/><div className="mt-8 inline-flex items-center gap-2 border border-border bg-background px-4 py-3 text-sm font-semibold"><FileCheck2 className="h-4 w-4 text-primary"/>Methodology standard · working framework</div></div><div className="evidence-sheet"><div className="flex items-center justify-between border-b border-border pb-5"><div><p className="font-mono text-[0.68rem] uppercase text-ink-muted">Evidence record</p><h3 className="mt-2 font-semibold">Publication integrity checklist</h3></div><span className="status-chip"><CircleDot className="h-3 w-3"/>Review ready</span></div>{["Source and collection method disclosed","Funding or commissioning party named","Update date and version history visible","Limitations stated in plain language","Download format and reuse terms specified"].map((item, i) => <div key={item} className="flex items-center gap-4 border-b border-border py-4 text-sm"><span className="flex h-6 w-6 items-center justify-center bg-primary-soft font-mono text-[0.65rem] text-primary">{i + 1}</span>{item}<Check className="ml-auto h-4 w-4 text-primary"/></div>)}</div></div><div className="mt-16 border-t border-border pt-10"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Insights</p><h3 className="mt-4 text-2xl font-semibold">Research built to be read, cited, and challenged.</h3></div><a href="#contact" className="inline-flex items-center gap-2 text-sm font-semibold text-primary">Partner on a tracker <ArrowRight className="h-4 w-4"/></a></div><div className="mt-8 grid gap-5 md:grid-cols-3">{[{type:"Reports & trackers",icon:FileText,text:"Method-led public evidence products with downloadable data and clear provenance."},{type:"Field notes",icon:BookOpen,text:"Concise observations from implementation, standards work, and institutional practice."},{type:"Briefings & webinars",icon:Microscope,text:"Focused sessions for public departments, compliance teams, and research partners."}].map((x) => <article key={x.type} className="border border-border bg-background p-6"><x.icon className="h-5 w-5 text-primary"/><h4 className="mt-5 font-semibold">{x.type}</h4><p className="mt-3 text-sm leading-relaxed text-ink-muted">{x.text}</p><p className="mt-6 font-mono text-[0.65rem] uppercase text-ink-muted">Publishing programme in development</p></article>)}</div></div></div></section>;
}

export function CtaSection() {
  return <section id="contact" className="section-pad bg-background"><div className="content-shell"><div className="grid gap-12 lg:grid-cols-[0.75fr_1.25fr]"><div><p className="eyebrow">Start a conversation</p><h2 className="mt-5 text-3xl leading-tight font-semibold sm:text-4xl">Bring us the institutional question—not a software shopping list.</h2><p className="mt-5 text-base leading-relaxed text-ink-muted">We’ll route your enquiry to the right conversation: a government briefing, enterprise demonstration, or research partnership discussion.</p><div className="mt-8 border-l-2 border-primary pl-5"><p className="text-sm font-semibold">Our boundary</p><p className="mt-2 text-sm leading-relaxed text-ink-muted">Publytics does not provide political targeting or persuasion systems to political parties or candidates.</p></div></div><BriefingForm/></div></div></section>;
}