/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as DpdpRouteImport } from './routes/dpdp'
import { Route as EngageRouteImport } from './routes/engage'
import { Route as PublicProofRouteImport } from './routes/public-proof'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as EvidenceIndexRouteImport } from './routes/evidence.index'
import { Route as EvidenceCorrectionsRouteImport } from './routes/evidence.corrections'
import { Route as EvidenceMethodStandardRouteImport } from './routes/evidence.method-standard'
import { Route as EvidenceRefusalLogRouteImport } from './routes/evidence.refusal-log'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const DpdpRoute = DpdpRouteImport.update({
  id: '/dpdp',
  path: '/dpdp',
  getParentRoute: () => rootRouteImport,
} as any)
const EngageRoute = EngageRouteImport.update({
  id: '/engage',
  path: '/engage',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicProofRoute = PublicProofRouteImport.update({
  id: '/public-proof',
  path: '/public-proof',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceIndexRoute = EvidenceIndexRouteImport.update({
  id: '/evidence/',
  path: '/evidence/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceCorrectionsRoute = EvidenceCorrectionsRouteImport.update({
  id: '/evidence/corrections',
  path: '/evidence/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceMethodStandardRoute = EvidenceMethodStandardRouteImport.update({
  id: '/evidence/method-standard',
  path: '/evidence/method-standard',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRefusalLogRoute = EvidenceRefusalLogRouteImport.update({
  id: '/evidence/refusal-log',
  path: '/evidence/refusal-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/dpdp': typeof DpdpRoute
  '/engage': typeof EngageRoute
  '/public-proof': typeof PublicProofRoute
  '/trust': typeof TrustRoute
  '/evidence/corrections': typeof EvidenceCorrectionsRoute
  '/evidence/method-standard': typeof EvidenceMethodStandardRoute
  '/evidence/refusal-log': typeof EvidenceRefusalLogRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/evidence/': typeof EvidenceIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/dpdp': typeof DpdpRoute
  '/engage': typeof EngageRoute
  '/public-proof': typeof PublicProofRoute
  '/trust': typeof TrustRoute
  '/evidence/corrections': typeof EvidenceCorrectionsRoute
  '/evidence/method-standard': typeof EvidenceMethodStandardRoute
  '/evidence/refusal-log': typeof EvidenceRefusalLogRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/evidence': typeof EvidenceIndexRoute
  '/products': typeof ProductsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/dpdp': typeof DpdpRoute
  '/engage': typeof EngageRoute
  '/public-proof': typeof PublicProofRoute
  '/trust': typeof TrustRoute
  '/evidence/corrections': typeof EvidenceCorrectionsRoute
  '/evidence/method-standard': typeof EvidenceMethodStandardRoute
  '/evidence/refusal-log': typeof EvidenceRefusalLogRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/evidence/': typeof EvidenceIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/dpdp'
    | '/engage'
    | '/public-proof'
    | '/trust'
    | '/evidence/corrections'
    | '/evidence/method-standard'
    | '/evidence/refusal-log'
    | '/products/$slug'
    | '/services/$slug'
    | '/solutions/$slug'
    | '/evidence/'
    | '/products/'
    | '/services/'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/dpdp'
    | '/engage'
    | '/public-proof'
    | '/trust'
    | '/evidence/corrections'
    | '/evidence/method-standard'
    | '/evidence/refusal-log'
    | '/products/$slug'
    | '/services/$slug'
    | '/solutions/$slug'
    | '/evidence'
    | '/products'
    | '/services'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/dpdp'
    | '/engage'
    | '/public-proof'
    | '/trust'
    | '/evidence/corrections'
    | '/evidence/method-standard'
    | '/evidence/refusal-log'
    | '/products/$slug'
    | '/services/$slug'
    | '/solutions/$slug'
    | '/evidence/'
    | '/products/'
    | '/services/'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRoute
  DpdpRoute: typeof DpdpRoute
  EngageRoute: typeof EngageRoute
  PublicProofRoute: typeof PublicProofRoute
  TrustRoute: typeof TrustRoute
  EvidenceCorrectionsRoute: typeof EvidenceCorrectionsRoute
  EvidenceMethodStandardRoute: typeof EvidenceMethodStandardRoute
  EvidenceRefusalLogRoute: typeof EvidenceRefusalLogRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  EvidenceIndexRoute: typeof EvidenceIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpdp': {
      id: '/dpdp'
      path: '/dpdp'
      fullPath: '/dpdp'
      preLoaderRoute: typeof DpdpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engage': {
      id: '/engage'
      path: '/engage'
      fullPath: '/engage'
      preLoaderRoute: typeof EngageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-proof': {
      id: '/public-proof'
      path: '/public-proof'
      fullPath: '/public-proof'
      preLoaderRoute: typeof PublicProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/': {
      id: '/evidence/'
      path: '/evidence'
      fullPath: '/evidence/'
      preLoaderRoute: typeof EvidenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/corrections': {
      id: '/evidence/corrections'
      path: '/evidence/corrections'
      fullPath: '/evidence/corrections'
      preLoaderRoute: typeof EvidenceCorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/method-standard': {
      id: '/evidence/method-standard'
      path: '/evidence/method-standard'
      fullPath: '/evidence/method-standard'
      preLoaderRoute: typeof EvidenceMethodStandardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/refusal-log': {
      id: '/evidence/refusal-log'
      path: '/evidence/refusal-log'
      fullPath: '/evidence/refusal-log'
      preLoaderRoute: typeof EvidenceRefusalLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRoute,
  DpdpRoute: DpdpRoute,
  EngageRoute: EngageRoute,
  PublicProofRoute: PublicProofRoute,
  TrustRoute: TrustRoute,
  EvidenceCorrectionsRoute: EvidenceCorrectionsRoute,
  EvidenceMethodStandardRoute: EvidenceMethodStandardRoute,
  EvidenceRefusalLogRoute: EvidenceRefusalLogRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  SolutionsSlugRoute: SolutionsSlugRoute,
  EvidenceIndexRoute: EvidenceIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
